/**
 * UUID helpers. Postgres primary keys are UUID v4 strings generated by
 * Prisma (`@default(uuid())`), so request-supplied ids are shape-checked
 * before they reach a query.
 */

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isUuid(value) {
  return UUID_RE.test(String(value || ''));
}

module.exports = { UUID_RE, isUuid };
